# Generated by Django 2.0.2 on 2018-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='caption',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
